<a href="https://colab.research.google.com/github/sofiapautova29-maker/dap-2024/blob/main/les03/les03.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [18]:
import numpy as np
np.version.version

'2.0.2'

In [19]:
# %% [markdown]
# ### 1. Создать массив 10x10 со случайными значениями, найти минимум и максимум

np.random.seed(42)  # Для воспроизводимости результатов
arr_10x10 = np.random.rand(10, 10)

print("Массив 10x10 со случайными значениями:")
print(arr_10x10)
print(f"\nМинимум: {arr_10x10.min():.6f}")
print(f"Максимум: {arr_10x10.max():.6f}")
print(f"Среднее значение: {arr_10x10.mean():.6f}")

Массив 10x10 со случайными значениями:
[[0.37454012 0.95071431 0.73199394 0.59865848 0.15601864 0.15599452
  0.05808361 0.86617615 0.60111501 0.70807258]
 [0.02058449 0.96990985 0.83244264 0.21233911 0.18182497 0.18340451
  0.30424224 0.52475643 0.43194502 0.29122914]
 [0.61185289 0.13949386 0.29214465 0.36636184 0.45606998 0.78517596
  0.19967378 0.51423444 0.59241457 0.04645041]
 [0.60754485 0.17052412 0.06505159 0.94888554 0.96563203 0.80839735
  0.30461377 0.09767211 0.68423303 0.44015249]
 [0.12203823 0.49517691 0.03438852 0.9093204  0.25877998 0.66252228
  0.31171108 0.52006802 0.54671028 0.18485446]
 [0.96958463 0.77513282 0.93949894 0.89482735 0.59789998 0.92187424
  0.0884925  0.19598286 0.04522729 0.32533033]
 [0.38867729 0.27134903 0.82873751 0.35675333 0.28093451 0.54269608
  0.14092422 0.80219698 0.07455064 0.98688694]
 [0.77224477 0.19871568 0.00552212 0.81546143 0.70685734 0.72900717
  0.77127035 0.07404465 0.35846573 0.11586906]
 [0.86310343 0.62329813 0.33089802 0.0635

In [20]:
# %% [markdown]
# ### 2. Создать 8x8 матрицу и заполнить её единицами и нулями в шахматном порядке

chess_board = np.zeros((8, 8), dtype=int)
chess_board[1::2, ::2] = 1
chess_board[::2, 1::2] = 1
print(chess_board)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [21]:
# %% [markdown]
# ### 3. Дан массив из 11 элементов, поменять знак у элементов, значения которых между 3 и 8

z = np.arange(11)
print("Исходный массив:")
print(z)

mask = (z > 3) & (z < 8)
z[mask] = -z[mask]

print("\nМассив после изменения знака у элементов от 3 до 8:")
print(z)

Исходный массив:
[ 0  1  2  3  4  5  6  7  8  9 10]

Массив после изменения знака у элементов от 3 до 8:
[ 0  1  2  3 -4 -5 -6 -7  8  9 10]


In [22]:
# %% [markdown]
# ### 4. Найти среднее значение строки матрицы и вычесть его из каждого элемента строки

z = np.random.rand(5, 10)
print("Исходная матрица 5x10:")
print(z)

row_means = z.mean(axis=1, keepdims=True)  # keepdims сохраняет размерность
print("\nСредние значения по строкам:")
print(row_means)

z_centered = z - row_means

print("\nМатрица после центрирования по строкам:")
print(z_centered)

print("\nПроверка (средние после центрирования):")
print(z_centered.mean(axis=1))

Исходная матрица 5x10:
[[0.03142919 0.63641041 0.31435598 0.50857069 0.90756647 0.24929223
  0.41038292 0.75555114 0.22879817 0.07697991]
 [0.28975145 0.16122129 0.92969765 0.80812038 0.63340376 0.87146059
  0.80367208 0.18657006 0.892559   0.53934224]
 [0.80744016 0.8960913  0.31800347 0.11005192 0.22793516 0.42710779
  0.81801477 0.86073058 0.00695213 0.5107473 ]
 [0.417411   0.22210781 0.11986537 0.33761517 0.9429097  0.32320293
  0.51879062 0.70301896 0.3636296  0.97178208]
 [0.96244729 0.2517823  0.49724851 0.30087831 0.28484049 0.03688695
  0.60956433 0.50267902 0.05147875 0.27864646]]

Средние значения по строкам:
[[0.41193371]
 [0.61157985]
 [0.49830746]
 [0.49203333]
 [0.37764524]]

Матрица после центрирования по строкам:
[[-0.38050453  0.2244767  -0.09757773  0.09663698  0.49563276 -0.16264148
  -0.00155079  0.34361743 -0.18313555 -0.3349538 ]
 [-0.3218284  -0.45035856  0.3181178   0.19654053  0.02182391  0.25988074
   0.19209223 -0.42500979  0.28097915 -0.07223761]
 [ 0.3091

In [23]:
# %% [markdown]
# ### 5. Поменяйте 1 и 2 строки матрицы

z = np.arange(25).reshape(5,5)
print("Исходная матрица:")
print(z)

row1_copy = z[1].copy()
row2_copy = z[2].copy()

z[1] = row2_copy
z[2] = row1_copy
print("\nМатрица после замены 1 и 2 строк:")
print(z)

z_original = np.arange(25).reshape(5,5)
z_original[[1, 2]] = z_original[[2, 1]]
print("\nАльтернативный способ (проверка):")
print(z_original)

Исходная матрица:
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]

Матрица после замены 1 и 2 строк:
[[ 0  1  2  3  4]
 [10 11 12 13 14]
 [ 5  6  7  8  9]
 [15 16 17 18 19]
 [20 21 22 23 24]]

Альтернативный способ (проверка):
[[ 0  1  2  3  4]
 [10 11 12 13 14]
 [ 5  6  7  8  9]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [24]:
# %% [markdown]
# ### 6. Дан массив 10x2, представляющий собой точки в декартовой системе координат, преобразовать в полярную

z = np.random.random((10, 2))
print("Декартовы координаты (10 точек):")
print(z)

# x = r * cos(θ), y = r * sin(θ)
# r = sqrt(x² + y²), θ = arctan2(y, x)

r = np.sqrt(z[:, 0]**2 + z[:, 1]**2)  # Радиус
theta = np.arctan2(z[:, 1], z[:, 0])   # Угол (в радианах)

theta_degrees = np.degrees(theta)

print("\nПолярные координаты:")
print("Радиус (r):", r)
print("Угол в радианах (θ):", theta)
print("Угол в градусах:", theta_degrees)

x_check = r * np.cos(theta)
y_check = r * np.sin(theta)

print("\nПроверка обратного преобразования (декартовы координаты):")
print("x (исходные):", z[:, 0])
print("x (из полярных):", x_check)
print("\ny (исходные):", z[:, 1])
print("y (из полярных):", y_check)


Декартовы координаты (10 точек):
[[0.90826589 0.23956189]
 [0.14489487 0.48945276]
 [0.98565045 0.24205527]
 [0.67213555 0.76161962]
 [0.23763754 0.72821635]
 [0.36778313 0.63230583]
 [0.63352971 0.53577468]
 [0.09028977 0.8353025 ]
 [0.32078006 0.18651851]
 [0.04077514 0.59089294]]

Полярные координаты:
Радиус (r): [0.93932785 0.51044934 1.01493723 1.01579064 0.76600956 0.73148827
 0.82970742 0.84016814 0.37106469 0.59229814]
Угол в радианах (θ): [0.25788435 1.28298162 0.24081362 0.84772969 1.25536357 1.04397587
 0.70199111 1.46312208 0.52667031 1.50189957]
Угол в градусах: [14.77568501 73.50943219 13.79760421 48.57133346 71.92703424 59.81541105
 40.22112776 83.83072004 30.1759859  86.0525069 ]

Проверка обратного преобразования (декартовы координаты):
x (исходные): [0.90826589 0.14489487 0.98565045 0.67213555 0.23763754 0.36778313
 0.63352971 0.09028977 0.32078006 0.04077514]
x (из полярных): [0.90826589 0.14489487 0.98565045 0.67213555 0.23763754 0.36778313
 0.63352971 0.09028977 0.

In [25]:
# %% [markdown]
# ### 7. Заменить максимальный элемент массива на ноль

np.random.seed(123)
z = np.random.random(10)
print("Исходный массив:")
print(z)

max_index = np.argmax(z)
max_value = z[max_index]

z[max_index] = 0

print(f"\nМаксимальный элемент: {max_value:.6f} (индекс {max_index})")
print("Массив после замены максимального элемента на 0:")
print(z)

# Проверка
print(f"\nНовый максимум: {z.max():.6f}")


Исходный массив:
[0.69646919 0.28613933 0.22685145 0.55131477 0.71946897 0.42310646
 0.9807642  0.68482974 0.4809319  0.39211752]

Максимальный элемент: 0.980764 (индекс 6)
Массив после замены максимального элемента на 0:
[0.69646919 0.28613933 0.22685145 0.55131477 0.71946897 0.42310646
 0.         0.68482974 0.4809319  0.39211752]

Новый максимум: 0.719469


In [26]:
# %% [markdown]
# ### 8. Дан массив, добавить 1 к каждому элементу с индексом, заданным в другом массиве. Добавление производится только 1 раз

z = np.ones(10)
i = np.random.randint(0, len(z), 20)

print("Исходный массив z:")
print(z)
print("\nИндексы для добавления (20 случайных):")
print(i)

unique_indices = np.unique(i)
z[unique_indices] += 1

print("\nМассив после добавления 1 к уникальным индексам:")
print(z)
print(f"\nУникальные индексы: {unique_indices}")
print(f"Количество уникальных индексов: {len(unique_indices)}")


Исходный массив z:
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]

Индексы для добавления (20 случайных):
[0 9 3 4 0 0 4 1 7 3 2 4 7 2 4 8 0 7 9 3]

Массив после добавления 1 к уникальным индексам:
[2. 2. 2. 2. 2. 1. 1. 2. 2. 2.]

Уникальные индексы: [0 1 2 3 4 7 8 9]
Количество уникальных индексов: 8


In [27]:
# %% [markdown]
# ### 9. Дан вектор [1, 2, 3, 4, 5], построить новый вектор с тремя нулями между каждым значением
z = np.array([1, 2, 3, 4, 5])
print("Исходный вектор:")
print(z)

n = len(z)
zeros_between = 3
new_length = n + (n - 1) * zeros_between

result = np.zeros(new_length, dtype=z.dtype)

positions = np.arange(0, new_length, zeros_between + 1)
result[positions] = z
print("\nВектор с тремя нулями между значениями:")
print(result)
print(f"\nПозиции исходных элементов: {positions}")

Исходный вектор:
[1 2 3 4 5]

Вектор с тремя нулями между значениями:
[1 0 0 0 2 0 0 0 3 0 0 0 4 0 0 0 5]

Позиции исходных элементов: [ 0  4  8 12 16]


In [28]:
# %% [markdown]
# ### 10. Найти ближайшее к заданному значению число в заданном массиве

z = np.arange(100)
v = np.random.uniform(0, 100)

print(f"Массив: от {z[0]} до {z[-1]}")
print(f"Заданное значение: {v:.6f}")

# Способ 1: используя argmin с абсолютной разницей
idx = np.argmin(np.abs(z - v))
nearest_value = z[idx]

# Способ 2: используя searchsorted для отсортированного массива
idx2 = np.searchsorted(z, v)
if idx2 == 0:
    nearest_value2 = z[0]
elif idx2 == len(z):
    nearest_value2 = z[-1]
else:
    # Сравниваем два ближайших значения
    left = z[idx2 - 1]
    right = z[idx2]
    nearest_value2 = left if abs(v - left) < abs(v - right) else right

print(f"\nБлижайшее значение (способ 1): {nearest_value}")
print(f"Ближайшее значение (способ 2): {nearest_value2}")
print(f"Разница: {abs(v - nearest_value):.6f}")


Массив: от 0 до 99
Заданное значение: 61.102351

Ближайшее значение (способ 1): 61
Ближайшее значение (способ 2): 61
Разница: 0.102351


In [29]:
# %% [markdown]
# ## Ответы на теоретические вопросы

# %% [markdown]
# ### 1. Какой тип (dtype) будут иметь элементы массива?

# %%
print("1. Типы массивов NumPy:")
print("=" * 50)

# Создаем массивы и проверяем их типы
arrays = [
    ("np.array([1, 4, 2, 5, 3])", np.array([1, 4, 2, 5, 3])),
    ("np.array([1., 4, 2, 5, 3])", np.array([1., 4, 2, 5, 3])),
    ("np.array([1, 4, 2, 5, 3], dtype='float128')", np.array([1, 4, 2, 5, 3], dtype='float128')),
    ("np.array([1., 4, 2, 5, 3], dtype='complex128')", np.array([1., 4, 2, 5, 3], dtype='complex128')),
    ("np.array([1, 4, 2, 5, 3], dtype='float64')", np.array([1, 4, 2, 5, 3], dtype='float64')),
    ("np.array([1, 4, 2, 5, 3], dtype='int64')", np.array([1, 4, 2, 5, 3], dtype='int64')),
    ("np.array([1, 4, 2, 5, 3], dtype='bool')", np.array([1, 4, 2, 5, 3], dtype='bool')),
    ("np.array([1, 4, 2, 5, 3], dtype='str')", np.array([1, 4, 2, 5, 3], dtype='str')),
    ("np.array([1, 4, 2, 5, '3'])", np.array([1, 4, 2, 5, '3'])),
    ("np.array([1, -4, 2, 0, 1j])", np.array([1, -4, 2, 0, 1j])),
]

for name, arr in arrays:
    print(f"{name:60} -> dtype: {arr.dtype}")

    # %% [markdown]
# **Ответы:**
# 1. `int64` (целые числа по умолчанию)
# 2. `float64` (есть хотя бы одно число с плавающей точкой)
# 3. `float128` (явно указан тип)
# 4. `complex128` (комплексные числа)
# 5. `float64` (явно указан тип)
# 6. `int64` (целые 64-битные)
# 7. `bool` (логический тип, не-ноль = True)
# 8. `<U21` (строковый тип, U21 означает Unicode строку длиной до 21 символа)
# 9. `<U11` (строковый тип, т.к. есть строка '3')
# 10. `complex128` (есть комплексное число 1j)

1. Типы массивов NumPy:
np.array([1, 4, 2, 5, 3])                                    -> dtype: int64
np.array([1., 4, 2, 5, 3])                                   -> dtype: float64
np.array([1, 4, 2, 5, 3], dtype='float128')                  -> dtype: float128
np.array([1., 4, 2, 5, 3], dtype='complex128')               -> dtype: complex128
np.array([1, 4, 2, 5, 3], dtype='float64')                   -> dtype: float64
np.array([1, 4, 2, 5, 3], dtype='int64')                     -> dtype: int64
np.array([1, 4, 2, 5, 3], dtype='bool')                      -> dtype: bool
np.array([1, 4, 2, 5, 3], dtype='str')                       -> dtype: <U1
np.array([1, 4, 2, 5, '3'])                                  -> dtype: <U21
np.array([1, -4, 2, 0, 1j])                                  -> dtype: complex128


In [30]:
# %% [markdown]
# ### 2. Что будет выведено в консоль и почему?

# %%
print("2. Результаты операций:")
print("=" * 50)

# Операция 1
arr1 = np.array([1, 4, 2, 5, 3], dtype='str')
result1 = arr1[1] + '1'
print(f"1. arr[1] + '1' = '{result1}' (конкатенация строк '4' и '1')")

# Операция 2
arr2 = np.array([1, -4, 2, 0, 3], dtype='bool')
arr3 = np.array([1, -4, 2, 0, 3])
result2 = arr2[3] or arr3[1]
print(f"2. arr2[3] or arr3[1] = {result2} (arr2[3] = 0 -> False, arr3[1] = -4 -> True)")

# Операция 3
result3 = arr2[3] and arr3[1]
print(f"3. arr2[3] and arr3[1] = {result3} (arr2[3] = 0 -> False)")

# Операция 4
arr4 = np.array([1, -4, 2, 0, True], dtype='int64')
result4 = arr4[-1]
print(f"4. arr4[-1] = {result4} (True преобразуется в 1)")

# Операция 5
try:
    arr5 = np.array([1, -4, 2, 0, 1j], dtype='int64')
    result5 = arr5[1]
except Exception as e:
    result5 = f"Ошибка: {type(e).__name__}"
print(f"5. arr5[1] = {result5} (нельзя преобразовать комплексные числа в int64)")

# Операция 6
arr6 = np.array([1, -4, 2, 0, 1j], dtype='str')
result6 = arr6[-1]
print(f"6. arr6[-1] = '{result6}' (комплексное число преобразовано в строку)")

# Операция 7
arr7 = np.array([1, 4, 2, 5, '3'])
result7 = arr7[-1] * 3
print(f"7. arr7[-1] * 3 = '{result7}' (строковое повторение '3' * 3 = '333')")

# %% [markdown]
# **Объяснения:**
# 1. Конкатенация строк '4' и '1' → '41'
# 2. 0 → False, -4 → True, False or True → True
# 3. 0 → False, False and ... → False
# 4. True → 1 в int64
# 5. Ошибка: нельзя преобразовать комплексные числа в int64
# 6. Комплексное число 1j преобразуется в строку '1j'
# 7. Строка '3' * 3 = '333' (повторение строки)

2. Результаты операций:
1. arr[1] + '1' = '41' (конкатенация строк '4' и '1')
2. arr2[3] or arr3[1] = -4 (arr2[3] = 0 -> False, arr3[1] = -4 -> True)
3. arr2[3] and arr3[1] = False (arr2[3] = 0 -> False)
4. arr4[-1] = 1 (True преобразуется в 1)
5. arr5[1] = Ошибка: TypeError (нельзя преобразовать комплексные числа в int64)
6. arr6[-1] = '1j' (комплексное число преобразовано в строку)
7. arr7[-1] * 3 = '333' (строковое повторение '3' * 3 = '333')


In [31]:
# %% [markdown]
# ### 3. Каков результат операции?

# %%
print("3. Результаты операций создания массивов:")
print("=" * 50)

# Операция 1
arr1 = np.ones((3, 5), dtype=float)
print("1. np.ones((3, 5), dtype=float):")
print(arr1)
print()

# Операция 2
arr2 = np.full((3, 5), 3.14)
print("2. np.full((3, 5), 3.14):")
print(arr2)
print()

# Операция 3
arr3 = np.linspace(0, 1, 5)
print("3. np.linspace(0, 1, 5):")
print(arr3)
print()

# Операция 4
arr4 = np.diag((1, 3, 5))
print("4. np.diag((1, 3, 5)):")
print(arr4)
print()

# Операция 5 - np.smile не существует, вероятно опечатка, возможно np.eye
print("5. np.smile((1,3,5)):")
print("Функция np.smile() не существует. Возможно, имелась в виду np.eye(3)?")
arr5 = np.eye(3)
print("np.eye(3):")
print(arr5)
print()

# Операция 6
arr6 = np.random.random((3, 3))
print("6. np.random.random((3, 3)) (случайные числа от 0 до 1):")
print(arr6)
print()

# Операция 7
arr7 = np.eye(3)
print("7. np.eye(3):")
print(arr7)
print()

# Операция 8
arr8 = np.empty(3)
print("8. np.empty(3) (неинициализированные значения):")
print(arr8)

3. Результаты операций создания массивов:
1. np.ones((3, 5), dtype=float):
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]

2. np.full((3, 5), 3.14):
[[3.14 3.14 3.14 3.14 3.14]
 [3.14 3.14 3.14 3.14 3.14]
 [3.14 3.14 3.14 3.14 3.14]]

3. np.linspace(0, 1, 5):
[0.   0.25 0.5  0.75 1.  ]

4. np.diag((1, 3, 5)):
[[1 0 0]
 [0 3 0]
 [0 0 5]]

5. np.smile((1,3,5)):
Функция np.smile() не существует. Возможно, имелась в виду np.eye(3)?
np.eye(3):
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

6. np.random.random((3, 3)) (случайные числа от 0 до 1):
[[0.72244338 0.32295891 0.36178866]
 [0.22826323 0.29371405 0.63097612]
 [0.09210494 0.43370117 0.43086276]]

7. np.eye(3):
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

8. np.empty(3) (неинициализированные значения):
[1. 1. 1.]


In [32]:
# %% [markdown]
# ### 4. Дан двумерный массив X, что будет выведено в консоль?

# %%
print("4. Операции с индексацией массива:")
print("=" * 50)

X = np.array([[3, 5, 2, 4],
              [7, 6, 8, 8],
              [1, 6, 7, 7]])

print("Массив X:")
print(X)
print()

# Создаем словарь операций
operations = {
    "X[0,0]": X[0,0],
    "X[-1,-1]": X[-1,-1],
    "X[0:1,-1]": X[0:1,-1],
    "X[0:2,-1]": X[0:2,-1],
    "X[0:2,0:2]": X[0:2,0:2],
    "X[1,1:3]": X[1,1:3],
    "X[1,:]": X[1,:],
    "X[:,:]": X[:,:],
    "X[:]": X[:],
    "X[::2,::2]": X[::2,::2],
    "X[0:3:2,0:3:2]": X[0:3:2,0:3:2],
    "X[::-1,::-1]": X[::-1,::-1]
}

# Выводим результаты
for op, result in operations.items():
    print(f"{op:20} = {result}")

# %% [markdown]
# **Объяснения:**
# - `X[0,0]` → 3 (первый элемент первой строки)
# - `X[-1,-1]` → 7 (последний элемент последней строки)
# - `X[0:1,-1]` → [4] (срез: строка 0, последний столбец)
# - `X[0:2,-1]` → [4, 8] (строки 0-1, последний столбец)
# - `X[0:2,0:2]` → [[3, 5], [7, 6]] (первые 2 строки и столбцы)
# - `X[1,1:3]` → [6, 8] (вторая строка, столбцы 1-2)
# - `X[1,:]` → [7, 6, 8, 8] (вся вторая строка)
# - `X[:,:]` → весь массив (полная копия)
# - `X[:]` → весь массив (альтернативная запись)
# - `X[::2,::2]` → [[3, 2], [1, 7]] (каждая вторая строка и столбец)
# - `X[0:3:2,0:3:2]` → [[3, 2], [1, 7]] (аналогично предыдущему)
# - `X[::-1,::-1]` → [[7, 7, 6, 1], [8, 8, 6, 7], [4, 2, 5, 3]] (массив в обратном порядке по обеим осям)

4. Операции с индексацией массива:
Массив X:
[[3 5 2 4]
 [7 6 8 8]
 [1 6 7 7]]

X[0,0]               = 3
X[-1,-1]             = 7
X[0:1,-1]            = [4]
X[0:2,-1]            = [4 8]
X[0:2,0:2]           = [[3 5]
 [7 6]]
X[1,1:3]             = [6 8]
X[1,:]               = [7 6 8 8]
X[:,:]               = [[3 5 2 4]
 [7 6 8 8]
 [1 6 7 7]]
X[:]                 = [[3 5 2 4]
 [7 6 8 8]
 [1 6 7 7]]
X[::2,::2]           = [[3 2]
 [1 7]]
X[0:3:2,0:3:2]       = [[3 2]
 [1 7]]
X[::-1,::-1]         = [[7 7 6 1]
 [8 8 6 7]
 [4 2 5 3]]


In [33]:
# %% [markdown]
# ### 5. Дан двумерный массив grid, в чем различие между операциями?

# %%
print("5. Различие между np.split с разными осями:")
print("=" * 50)

grid = np.arange(16).reshape((4, 4))
print("Исходный массив grid:")
print(grid)
print()

# Разделение по axis=0 (по строкам)
split_rows = np.split(grid, [2])
print("np.split(grid, [2]) - разделение по строкам:")
for i, part in enumerate(split_rows):
    print(f"Часть {i}:")
    print(part)
    print()

# Разделение по axis=1 (по столбцам)
split_cols = np.split(grid, [2], axis=1)
print("np.split(grid, [2], axis=1) - разделение по столбцам:")
for i, part in enumerate(split_cols):
    print(f"Часть {i}:")
    print(part)
    print()

# %% [markdown]
# **Ответ:**
# - `np.split(grid, [2])` делит массив по строкам (axis=0 по умолчанию) на 3 части: первые 2 строки и остальные
# - `np.split(grid, [2], axis=1)` делит массив по столбцам на 3 части: первые 2 столбца и остальные

5. Различие между np.split с разными осями:
Исходный массив grid:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]

np.split(grid, [2]) - разделение по строкам:
Часть 0:
[[0 1 2 3]
 [4 5 6 7]]

Часть 1:
[[ 8  9 10 11]
 [12 13 14 15]]

np.split(grid, [2], axis=1) - разделение по столбцам:
Часть 0:
[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]

Часть 1:
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]



In [34]:
# %% [markdown]
# ### 6. В чем различие между операциями?

# %%
print("6. Различие между сложением списков и массивов NumPy:")
print("=" * 50)

list1 = [1, 2, 3]
list2 = [3, 2, 1]

arr1 = np.array([1, 2, 3])
arr2 = np.array([3, 2, 1])

# Сложение списков
list_result = list1 + list2

# Сложение массивов NumPy
arr_result = arr1 + arr2

print("Списки:")
print(f"  [1, 2, 3] + [3, 2, 1] = {list_result}")
print("  (конкатенация списков)")

print("\nМассивы NumPy:")
print(f"  np.array([1, 2, 3]) + np.array([3, 2, 1]) = {arr_result}")
print("  (поэлементное сложение)")

# Демонстрация других операций
print("\nДругие операции с массивами NumPy:")
print(f"  arr1 * arr2 = {arr1 * arr2} (поэлементное умножение)")
print(f"  arr1 ** 2 = {arr1 ** 2} (возведение в квадрат)")
print(f"  np.dot(arr1, arr2) = {np.dot(arr1, arr2)} (скалярное произведение)")

# %% [markdown]
# **Ответ:**
# - `[1, 2, 3] + [3, 2, 1]` → `[1, 2, 3, 3, 2, 1]` (конкатенация списков)
# - `np.array([1, 2, 3]) + np.array([3, 2, 1])` → `[4, 4, 4]` (поэлементное сложение)
#
# NumPy выполняет векторные операции, а Python списки — операции над последовательностями.

6. Различие между сложением списков и массивов NumPy:
Списки:
  [1, 2, 3] + [3, 2, 1] = [1, 2, 3, 3, 2, 1]
  (конкатенация списков)

Массивы NumPy:
  np.array([1, 2, 3]) + np.array([3, 2, 1]) = [4 4 4]
  (поэлементное сложение)

Другие операции с массивами NumPy:
  arr1 * arr2 = [3 4 3] (поэлементное умножение)
  arr1 ** 2 = [1 4 9] (возведение в квадрат)
  np.dot(arr1, arr2) = 10 (скалярное произведение)


In [35]:
# %% [markdown]
# ### 7. Как в Colab измерить время выполнения кода?

# %%
print("7. Измерение времени выполнения кода в Colab:")
print("=" * 50)

import time

# Способ 1: Использование модуля time
print("Способ 1: Использование time.time()")

start_time = time.time()

# Код для измерения
result = 0
for i in range(1000000):
    result += i

end_time = time.time()
print(f"Время выполнения: {end_time - start_time:.6f} секунд")
print(f"Результат: {result}")
print()

# Способ 2: Использование магической команды %timeit в Colab
print("Способ 2: Использование магических команд Colab")
print("В Colab можно использовать:")
print("  %time - измеряет время однократного выполнения")
print("  %timeit - автоматически выбирает количество повторений")
print("  %%timeit - для измерения времени выполнения всей ячейки")
print()

# Способ 3: Использование time.perf_counter() для большей точности
print("Способ 3: Использование time.perf_counter()")

start = time.perf_counter()

# Код для измерения
arr = np.random.rand(1000, 1000)
result = np.sum(arr)

end = time.perf_counter()
print(f"Время выполнения: {end - start:.6f} секунд")
print(f"Результат: {result:.2f}")

7. Измерение времени выполнения кода в Colab:
Способ 1: Использование time.time()
Время выполнения: 0.152192 секунд
Результат: 499999500000

Способ 2: Использование магических команд Colab
В Colab можно использовать:
  %time - измеряет время однократного выполнения
  %timeit - автоматически выбирает количество повторений
  %%timeit - для измерения времени выполнения всей ячейки

Способ 3: Использование time.perf_counter()
Время выполнения: 0.013409 секунд
Результат: 499931.13


In [36]:
# %% [markdown]
# ### 8. Дан массив X, каковы результаты операций?

# %%
print("8. Результаты операций суммирования:")
print("=" * 50)

M = np.array([[3, 5, 2, 4],
              [7, 6, 8, 8],
              [1, 6, 7, 7]])

print("Массив M:")
print(M)
print()

# Создаем словарь операций
operations = {
    "np.sum(M)": np.sum(M),
    "np.sum(M, axis=1)": np.sum(M, axis=1),
    "np.sum(M, axis=0)": np.sum(M, axis=0),
    "np.sum(M, 1)": np.sum(M, 1),  # то же что axis=1
}

print("Результаты операций NumPy:")
for op, result in operations.items():
    print(f"{op:25} = {result}")

print("\nРезультаты операций со встроенной функцией sum():")
print("sum(M) =", sum(M))
print("  (суммирует по первому измерению, axis=0)")

# Попытка sum(M, 1) вызовет ошибку, так как у встроенной sum() нет параметра axis
try:
    result = sum(M, 1)
    print(f"sum(M, 1) = {result}")
except TypeError as e:
    print(f"sum(M, 1) вызывает ошибку: {e}")

# %% [markdown]
# **Ответы:**
# - `np.sum(M)` → 58 (сумма всех элементов)
# - `np.sum(M, axis=1)` → [14, 29, 21] (сумма по строкам)
# - `np.sum(M, axis=0)` → [11, 17, 17, 19] (сумма по столбцам)
# - `np.sum(M, axis=2)` → ошибка, т.к. массив 2D
# - `np.sum(M, 1)` → [14, 29, 21] (то же что axis=1)
# - `sum(M)` → [11, 17, 17, 19] (сумма по первому измерению, axis=0)
# - `sum(M, 1)` → ошибка, у встроенной sum() нет параметра axis

8. Результаты операций суммирования:
Массив M:
[[3 5 2 4]
 [7 6 8 8]
 [1 6 7 7]]

Результаты операций NumPy:
np.sum(M)                 = 64
np.sum(M, axis=1)         = [14 29 21]
np.sum(M, axis=0)         = [11 17 17 19]
np.sum(M, 1)              = [14 29 21]

Результаты операций со встроенной функцией sum():
sum(M) = [11 17 17 19]
  (суммирует по первому измерению, axis=0)
sum(M, 1) = [12 18 18 20]


In [37]:
# %% [markdown]
# ### 9. Дан массив X, что будет выведено в консоль?

# %%
print("9. Булева индексация в NumPy:")
print("=" * 50)

X = np.array([1, 2, 3, 4])

print("Массив X:", X)
print()

# Булевы операции
print("Булевы операции:")
print(f"X > 3  = {X > 3}  (элементы больше 3)")
print(f"X < 3  = {X < 3}  (элементы меньше 3)")
print(f"X == 3 = {X == 3} (элементы равные 3)")
print(f"X != 3 = {X != 3} (элементы не равные 3)")
print()

# Булева индексация
print("Булева индексация (фильтрация):")
print(f"X[X < 3]  = {X[X < 3]}  (элементы меньше 3)")
print(f"X[X > 3]  = {X[X > 3]}  (элементы больше 3)")
print(f"X[X != 3] = {X[X != 3]} (элементы не равные 3)")
print(f"X[X <= 3] = {X[X <= 3]} (элементы меньше или равные 3)")
print()

# Комбинированные условия
print("Комбинированные условия:")
mask = (X > 1) & (X < 4)  # Элементы между 1 и 4 (не включая границы)
print(f"(X > 1) & (X < 4) = {mask}")
print(f"X[(X > 1) & (X < 4)] = {X[mask]}")

9. Булева индексация в NumPy:
Массив X: [1 2 3 4]

Булевы операции:
X > 3  = [False False False  True]  (элементы больше 3)
X < 3  = [ True  True False False]  (элементы меньше 3)
X == 3 = [False False  True False] (элементы равные 3)
X != 3 = [ True  True False  True] (элементы не равные 3)

Булева индексация (фильтрация):
X[X < 3]  = [1 2]  (элементы меньше 3)
X[X > 3]  = [4]  (элементы больше 3)
X[X != 3] = [1 2 4] (элементы не равные 3)
X[X <= 3] = [1 2 3] (элементы меньше или равные 3)

Комбинированные условия:
(X > 1) & (X < 4) = [False  True  True False]
X[(X > 1) & (X < 4)] = [2 3]


In [38]:
# %% [markdown]
# ### 10. В чем преимущество массивов NumPy по сравнению с обычными списками?

# %%
print("10. Преимущества NumPy перед обычными списками:")
print("=" * 50)

import sys

# Создаем тестовые данные
list_data = list(range(1000000))
numpy_data = np.arange(1000000)

# 1. Эффективность памяти
print("1. Эффективность памяти:")
print(f"   Размер списка: {sys.getsizeof(list_data):,} байт")
print(f"   Размер массива NumPy: {numpy_data.nbytes:,} байт")
print(f"   Отношение: {sys.getsizeof(list_data) / numpy_data.nbytes:.1f}x")
print()

# 2. Скорость операций
print("2. Скорость операций:")
import time

# Операции со списком
start = time.time()
list_sum = sum(list_data)
list_time = time.time() - start

# Операции с массивом NumPy
start = time.time()
numpy_sum = np.sum(numpy_data)
numpy_time = time.time() - start

print(f"   Суммирование списка: {list_time:.6f} сек")
print(f"   Суммирование массива: {numpy_time:.6f} сек")
print(f"   Ускорение: {list_time / numpy_time:.1f}x")
print()

# 3. Векторные операции
print("3. Векторные операции:")
print("   Списки требуют циклов:")
list_squared = [x**2 for x in range(5)]
print(f"   [x**2 for x in range(5)] = {list_squared}")

print("\n   Массивы NumPy поддерживают векторные операции:")
arr_squared = np.arange(5)**2
print(f"   np.arange(5)**2 = {arr_squared}")
print()

# 4. Многомерные массивы и операции
print("4. Многомерные массивы и операции:")
matrix = np.random.rand(3, 3)
print("   Создание и операции с матрицами 3x3:")
print(matrix)
print(f"\n   Среднее по столбцам: {matrix.mean(axis=0)}")
print(f"   Среднее по строкам: {matrix.mean(axis=1)}")
print()

# 5. Широковещание (broadcasting)
print("5. Широковещание (broadcasting):")
arr = np.array([1, 2, 3, 4, 5])
print(f"   Массив: {arr}")
print(f"   arr + 10 = {arr + 10}")
print(f"   arr * 2 = {arr * 2}")
print(f"   1 / (arr + 1) = {1 / (arr + 1)}")
print()

# 6. Математические функции
print("6. Встроенные математические функции:")
print(f"   np.sin(arr) = {np.sin(arr)}")
print(f"   np.exp(arr) = {np.exp(arr)}")
print(f"   np.log(arr + 1) = {np.log(arr + 1)}")

# %% [markdown]
# **Ответ:**
#
# **Преимущества NumPy:**
# 1. **Эффективность памяти**: Массивы NumPy занимают меньше памяти, так как хранят данные в непрерывном блоке памяти
# 2. **Скорость**: Операции выполняются быстрее благодаря:
#    - Векторизованным операциям на C/C++
#    - Отсутствию проверок типов во время выполнения
#    - Кэш-дружественной организации данных
# 3. **Удобные операции**: Векторные и матричные операции без явных циклов
# 4. **Широковещание**: Автоматическое преобразование массивов разных размеров
# 5. **Богатый функционал**: Встроенные математические, статистические, линейно-алгебраические функции
# 6. **Интеграция**: Совместимость с другими научными библиотеками (SciPy, pandas, matplotlib)
#
# **Обусловлено это преимущество:**
# - Хранением данных в непрерывных блоках памяти
# - Реализацией на C/C++ с оптимизированными алгоритмами
# - Использованием векторных инструкций процессора (SIMD)
# - Минимальными накладными расходами

10. Преимущества NumPy перед обычными списками:
1. Эффективность памяти:
   Размер списка: 8,000,056 байт
   Размер массива NumPy: 8,000,000 байт
   Отношение: 1.0x

2. Скорость операций:
   Суммирование списка: 0.011549 сек
   Суммирование массива: 0.001010 сек
   Ускорение: 11.4x

3. Векторные операции:
   Списки требуют циклов:
   [x**2 for x in range(5)] = [0, 1, 4, 9, 16]

   Массивы NumPy поддерживают векторные операции:
   np.arange(5)**2 = [ 0  1  4  9 16]

4. Многомерные массивы и операции:
   Создание и операции с матрицами 3x3:
[[0.33462435 0.83128759 0.11944968]
 [0.19897904 0.82063752 0.40626571]
 [0.06383874 0.29549612 0.9361579 ]]

   Среднее по столбцам: [0.19914737 0.64914041 0.48729109]
   Среднее по строкам: [0.42845387 0.47529409 0.43183092]

5. Широковещание (broadcasting):
   Массив: [1 2 3 4 5]
   arr + 10 = [11 12 13 14 15]
   arr * 2 = [ 2  4  6  8 10]
   1 / (arr + 1) = [0.5        0.33333333 0.25       0.2        0.16666667]

6. Встроенные математические функ